#!/usr/bin/env bash
# =============================================================================
# deploy.sh — Airflow on GKE Autopilot — One-Command Deployment
# Usage: ./deploy.sh <customer> <project_id> <environment> <vpn_cidr> <db_password> <dag_repo_ssh_url>
# Example: ./deploy.sh acme my-gcp-project dev 203.0.113.10/32 MyPassword123 git@github.com:acme/airflow-dags.git
# =============================================================================
set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
step()    { echo -e "\n${BLUE}══════════════════════════════════════════${NC}"; echo -e "${BLUE}STEP $*${NC}"; echo -e "${BLUE}══════════════════════════════════════════${NC}"; }

# ── Argument validation ───────────────────────────────────────────────────────
if [[ $# -lt 6 ]]; then
  echo "Usage: $0 <customer> <project_id> <environment> <vpn_cidr> <db_password> <dag_repo_ssh_url>"
  echo ""
  echo "Arguments:"
  echo "  customer        Short slug for the customer, e.g. acme-corp"
  echo "  project_id      GCP project ID, e.g. my-gcp-project"
  echo "  environment     dev or prod"
  echo "  vpn_cidr        Corporate VPN IP in CIDR, e.g. 203.0.113.10/32"
  echo "  db_password     Password for the Airflow Postgres user"
  echo "  dag_repo        SSH URL of the DAG repo, e.g. git@github.com:org/dags.git"
  exit 1
fi

CUSTOMER="$1"
PROJECT_ID="$2"
ENVIRONMENT="$3"
VPN_CIDR="$4"
DB_PASSWORD="$5"
DAG_REPO="$6"
REGION="us-central1"
CLUSTER_NAME="${CUSTOMER}-gke"
SQL_INSTANCE="${CUSTOMER}-airflow-pg-${ENVIRONMENT}"
GCS_BUCKET="${CUSTOMER}-airflow-logs-${ENVIRONMENT}"
SA_EMAIL="${CUSTOMER}-airflow-worker@${PROJECT_ID}.iam.gserviceaccount.com"
SSH_KEY_PATH="$HOME/.ssh/${CUSTOMER}_airflow_github_key"

# ── Pre-flight checks ─────────────────────────────────────────────────────────
step "0 — Pre-flight checks"

command -v gcloud  >/dev/null || error "gcloud not found. Install Google Cloud SDK."
command -v terraform >/dev/null || error "terraform not found. Install from https://terraform.io"
command -v helm    >/dev/null || error "helm not found. Install from https://helm.sh"
command -v kubectl >/dev/null || error "kubectl not found."
command -v ssh-keygen >/dev/null || error "ssh-keygen not found."

[[ "$ENVIRONMENT" == "dev" || "$ENVIRONMENT" == "prod" ]] || error "environment must be 'dev' or 'prod'"

# Check GCP auth
gcloud auth print-access-token >/dev/null 2>&1 || error "Not authenticated to GCP. Run: gcloud auth application-default login"
gcloud config set project "$PROJECT_ID" >/dev/null
success "All pre-flight checks passed"
info "Customer:    $CUSTOMER"
info "Project:     $PROJECT_ID"
info "Environment: $ENVIRONMENT"
info "Region:      $REGION"
info "VPN CIDR:    $VPN_CIDR"
info "DAG Repo:    $DAG_REPO"

# ── Step 1: Generate SSH Deploy Key ──────────────────────────────────────────
step "1 — SSH Deploy Key for Git-Sync"

if [[ -f "$SSH_KEY_PATH" ]]; then
  warn "SSH key already exists at $SSH_KEY_PATH — skipping generation"
else
  ssh-keygen -t ed25519 -C "airflow-git-sync-${CUSTOMER}" -f "$SSH_KEY_PATH" -N ""
  success "SSH key generated at $SSH_KEY_PATH"
fi

echo ""
echo -e "${YELLOW}ACTION REQUIRED:${NC}"
echo "Add the following public key to your DAG repo as a read-only Deploy Key:"
echo "  GitHub: $DAG_REPO → Settings → Deploy Keys → Add Deploy Key"
echo ""
cat "${SSH_KEY_PATH}.pub"
echo ""
read -p "Press ENTER after you have added the deploy key to GitHub..."

# ── Step 2: Generate values.yaml ─────────────────────────────────────────────
step "2 — Generating helm/values.yaml"

mkdir -p helm
cat > helm/values.yaml << YAML
# Auto-generated by deploy.sh for customer: ${CUSTOMER}
# Environment: ${ENVIRONMENT} | Project: ${PROJECT_ID}

executor: "KubernetesExecutor"

postgresql:
  enabled: false

data:
  metadataConnection:
    user: airflow
    pass: ${DB_PASSWORD}
    host: 127.0.0.1
    port: 5432
    db: airflow
    sslmode: disable

config:
  logging:
    remote_logging: "True"
    remote_base_log_folder: "gs://${GCS_BUCKET}/logs"
    remote_log_conn_id: "google_cloud_default"

serviceAccount:
  create: true
  name: "airflow-worker"
  annotations:
    iam.gke.io/gcp-service-account: "${SA_EMAIL}"

scheduler:
  waitForMigrations:
    enabled: false
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
  extraContainers:
    - name: cloud-sql-proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
      args: ["--private-ip", "--port=5432", "${PROJECT_ID}:${REGION}:${SQL_INSTANCE}"]
      resources:
        requests: { cpu: "50m", memory: "128Mi" }
        limits:   { cpu: "100m", memory: "256Mi" }
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false

webserver:
  waitForMigrations:
    enabled: false
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
  extraContainers:
    - name: cloud-sql-proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
      args: ["--private-ip", "--port=5432", "${PROJECT_ID}:${REGION}:${SQL_INSTANCE}"]
      resources:
        requests: { cpu: "50m", memory: "128Mi" }
        limits:   { cpu: "100m", memory: "256Mi" }
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false

triggerer:
  waitForMigrations:
    enabled: false
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
  extraContainers:
    - name: cloud-sql-proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
      args: ["--private-ip", "--port=5432", "${PROJECT_ID}:${REGION}:${SQL_INSTANCE}"]
      resources:
        requests: { cpu: "50m", memory: "128Mi" }
        limits:   { cpu: "100m", memory: "256Mi" }
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false

workers:
  nodeSelector:
    cloud.google.com/gke-spot: "true"
  tolerations:
    - key: "cloud.google.com/gke-spot"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
  extraContainers:
    - name: cloud-sql-proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
      args: ["--private-ip", "--port=5432", "${PROJECT_ID}:${REGION}:${SQL_INSTANCE}"]
      resources:
        requests: { cpu: "50m", memory: "128Mi" }
        limits:   { cpu: "100m", memory: "256Mi" }
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false

migrateDatabaseJob:
  extraContainers:
    - name: cloud-sql-proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
      args: ["--private-ip", "--port=5432", "${PROJECT_ID}:${REGION}:${SQL_INSTANCE}"]
      resources:
        requests: { cpu: "50m", memory: "128Mi" }
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false

createUserJob:
  extraContainers:
    - name: cloud-sql-proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
      args: ["--private-ip", "--port=5432", "${PROJECT_ID}:${REGION}:${SQL_INSTANCE}"]
      resources:
        requests: { cpu: "50m", memory: "128Mi" }
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false

dags:
  gitSync:
    enabled: true
    repo: "${DAG_REPO}"
    branch: "main"
    subPath: "dags"
    sshKeySecret: "airflow-ssh-git"

logs:
  persistence:
    enabled: false

webserverSecretKeySecretName: "airflow-webserver-secret-key"
YAML

success "helm/values.yaml generated"

# ── Step 3: Write terraform.tfvars ───────────────────────────────────────────
step "3 — Writing terraform/terraform.tfvars"

cat > terraform/terraform.tfvars << TFVARS
project_id          = "${PROJECT_ID}"
region              = "${REGION}"
customer            = "${CUSTOMER}"
environment         = "${ENVIRONMENT}"
authorized_vpn_cidr = "${VPN_CIDR}"
enable_spot_workers = true
dag_repo_url        = "${DAG_REPO}"
cloud_sql_tier      = "db-g1-small"
TFVARS

success "terraform/terraform.tfvars written (gitignored)"

# ── Step 4: Terraform — Infrastructure ───────────────────────────────────────
step "4 — Terraform: Provision Infrastructure"

cd terraform
terraform init -upgrade

info "Applying networking..."
terraform apply -target=module.networking -auto-approve

info "Applying database (this takes ~10 minutes)..."
terraform apply -target=module.db -auto-approve

info "Applying GKE cluster (this takes ~8 minutes)..."
terraform apply -target=module.gke -auto-approve

info "Applying IAM..."
terraform apply -target=module.iam -auto-approve

info "Applying storage bucket..."
terraform apply -target=google_storage_bucket.airflow_logs -auto-approve

info "Applying Secret Manager secret..."
terraform apply -target=google_secret_manager_secret.git_sync_ssh_key -auto-approve 2>/dev/null || true

cd ..
success "Infrastructure provisioned"

# ── Step 5: Connect kubectl ───────────────────────────────────────────────────
step "5 — Connecting kubectl to GKE cluster"

gcloud container clusters get-credentials "$CLUSTER_NAME" \
  --region "$REGION" \
  --project "$PROJECT_ID"

success "kubectl connected to $CLUSTER_NAME"

# ── Step 6: Cloud SQL — Create airflow user ───────────────────────────────────
step "6 — Creating Cloud SQL airflow user"

if gcloud sql users list --instance="$SQL_INSTANCE" --project="$PROJECT_ID" 2>/dev/null | grep -q "^airflow"; then
  warn "Cloud SQL user 'airflow' already exists — skipping"
else
  gcloud sql users create airflow \
    --instance="$SQL_INSTANCE" \
    --password="$DB_PASSWORD" \
    --project="$PROJECT_ID"
  success "Cloud SQL user 'airflow' created"
fi

# ── Step 7: Add all WI IAM bindings ──────────────────────────────────────────
step "7 — Workload Identity IAM bindings"

for KSA in airflow-worker airflow-scheduler airflow-webserver airflow-migrate-database-job airflow-create-user-job airflow-triggerer; do
  gcloud iam service-accounts add-iam-policy-binding "$SA_EMAIL" \
    --role="roles/iam.workloadIdentityUser" \
    --member="serviceAccount:${PROJECT_ID}.svc.id.goog[airflow/${KSA}]" \
    --project="$PROJECT_ID" \
    --condition=None \
    2>/dev/null || true
done

success "Workload Identity bindings applied for all Airflow service accounts"

# ── Step 8: Kubernetes namespace and secrets ──────────────────────────────────
step "8 — Kubernetes namespace and secrets"

kubectl create namespace airflow --dry-run=client -o yaml | kubectl apply -f -

# SSH key secret
kubectl create secret generic airflow-ssh-git \
  --from-file=gitSshKey="$SSH_KEY_PATH" \
  -n airflow \
  --dry-run=client -o yaml | kubectl apply -f -

# Webserver secret key
kubectl create secret generic airflow-webserver-secret-key \
  --from-literal=webserver-secret-key="$(python3 -c 'import secrets; print(secrets.token_hex(16))')" \
  -n airflow \
  --dry-run=client -o yaml | kubectl apply -f -

success "Namespace and secrets created"

# ── Step 9: Helm deploy ───────────────────────────────────────────────────────
step "9 — Deploying Airflow via Helm"

helm repo add apache-airflow https://airflow.apache.org 2>/dev/null || true
helm repo update

helm upgrade --install airflow apache-airflow/airflow \
  --namespace airflow \
  --values helm/values.yaml \
  --version 1.14.0 \
  --timeout 15m

# Annotate all service accounts with Workload Identity
for SA in airflow-scheduler airflow-webserver airflow-worker airflow-migrate-database-job airflow-triggerer; do
  kubectl annotate serviceaccount "$SA" -n airflow \
    iam.gke.io/gcp-service-account="$SA_EMAIL" \
    --overwrite 2>/dev/null || true
done

success "Airflow deployed"

# ── Step 10: Create admin user ────────────────────────────────────────────────
step "10 — Creating Airflow admin user"

info "Waiting 30s for scheduler to be ready..."
sleep 30

SCHEDULER_POD=$(kubectl get pod -n airflow -l component=scheduler -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "")

if [[ -n "$SCHEDULER_POD" ]]; then
  kubectl exec -n airflow "$SCHEDULER_POD" -c scheduler -- \
    airflow users create \
    --username admin \
    --password "Admin$(date +%Y)!" \
    --firstname Admin \
    --lastname User \
    --role Admin \
    --email "admin@${CUSTOMER}.com" 2>/dev/null || warn "Admin user may already exist"
  success "Admin user created — password: Admin$(date +%Y)!"
else
  warn "Scheduler not ready yet. Create admin user manually after deployment."
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}════════════════════════════════════════════${NC}"
echo -e "${GREEN}  DEPLOYMENT COMPLETE: ${CUSTOMER} / ${ENVIRONMENT}${NC}"
echo -e "${GREEN}════════════════════════════════════════════${NC}"
echo ""
echo "Access the Airflow UI:"
echo "  kubectl port-forward svc/airflow-webserver 8080:8080 -n airflow"
echo "  Then open: http://localhost:8080"
echo ""
echo "Credentials:"
echo "  Username: admin"
echo "  Password: Admin$(date +%Y)!"
echo ""
echo "To destroy all infrastructure:"
echo "  cd terraform && terraform destroy"
echo ""
